# Generated by Django 4.2.5 on 2023-09-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='product name')),
                ('brand', models.CharField(choices=[('AP', 'Apple'), ('MC', 'Microsoft'), ('NV', 'Nvidia'), ('RZ', 'Ryzen'), ('IN', 'Intel')], max_length=10)),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'My products',
                'ordering': ['name'],
            },
        ),
    ]
